name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
      - name: Install packages
        run: npm ci
      - name: Set Creds
        run: git config user.name "opmvpc" && git config user.email "thibsix@outlook.be"
      - name: Deploy
        run: npm run deploy
